// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  alternate_grid_2: dynamic(() => import("./AlternateGrid2")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  rich_text: dynamic(() => import("./RichText")),
};
